name: ever_after
description: "Wedding planner app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

#slidable-card
  flutter_slidable: ^3.0.0
#  shared_preferences: ^2.2.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

#  firebase integration
  firebase_core: ^4.1.0

#  for handling google Signin
  google_sign_in: ^6.2.2

#  fo handling firebase authentication
  firebase_auth: ^6.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

    #  icon
  flutter_launcher_icons: ^0.14.4
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/wedding-couple.png"
  min_sdk_android: 21
#  remove_alpha_ios: true

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
